### ISSUE TITLE
Descriptive parsing errors

### ISSUE THREAD

**Issue by sciguy16** [Ayrx/nmap_xml_parser#1]
Hi, I'm trying to load an nmap XML file  but it's failing to parse and I suspect it's because the `<hostnames/>` node is empty. It would be useful to have more descriptive parsing errors to help with debugging this. I'm happy to help out with this project and send some PRs your way.

Here's the nmap output I'm trying to parse:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 7.80 scan initiated Tue May 12 15:08:55 2020 as: nmap -p 3389 -oX nmap.xml 192.168.59.138 -->
<nmaprun scanner="nmap" args="nmap -p 3389 -oX nmap.xml 192.168.59.138" start="1589292535" startstr="Tue May 12 15:08:55 2020" version="7.80" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="1" services="3389"/>
<verbose level="0"/>
<debugging level="0"/>
<host starttime="1589292535" endtime="1589292535"><status state="up" reason="arp-response" reason_ttl="0"/>
<address addr="192.168.59.138" addrtype="ipv4"/>
<address addr="00:0C:29:71:23:2B" addrtype="mac" vendor="VMware"/>
<hostnames/>
<ports><port protocol="tcp" portid="3389"><state state="open" reason="syn-ack" reason_ttl="128"/><service name="ms-wbt-server" method="table" conf="3"/></port>
</ports>
<times srtt="507" rttvar="4017" to="100000"/>
</host>
<runstats><finished time="1589292536" timestr="Tue May 12 15:08:56 2020" elapsed="0.39" summary="Nmap done at Tue May 12 15:08:56 2020; 1 IP address (1 host up) scanned in 0.39 seconds" exit="success"/><hosts up="1" down="0" total="1"/>
</runstats>
</nmaprun>
```

**Comment by Ayrx** [comment]
Thanks! 

Yeah, this is something I threw together quickly and definitely needs a lot more work around error handling and edge cases. I'll see if I can improve it this weekend and I'll be happy to review any PRs you send my way :)

**Comment by Ayrx** [comment]
The error is in this
```
<address addr="00:0C:29:71:23:2B" addrtype="mac" vendor="VMware"/>
```

Obviously I completely forgot that the address could be a MAC instead of a IPv4 or IPv6. The `Host.ip_address` field needs to be changed to an Enum to handle this scenario properly. I'll put together a fix for this as soon as I can.

**Comment by Ayrx** [comment]
I'm going to reopen this to track the address node parsing issue.
