### ISSUE TITLE
`runstats` should be optional

### ISSUE THREAD

**Issue by sciguy16** [Ayrx/nmap_xml_parser#8]
I've got an nmap scan that I can to ctrl-c at the end because it had reached the stage where it kept saying "99.8%" and not really advancing. Consequently, there's no `runstats` node at the end of the file. I think that sticking runstats in an Option or a Result should be okay as it doesn't really affect the scan results, and it's reasonably common to have to ctrl+c at the end of slow scans.

**Comment by Ayrx** [comment]
Fixed in 41f278ffb4618a30a3d132538ca775861445b6e8. Sorry for the very long turnaround time on this!
